### ISSUE TITLE
Thanks for sharing, no plist.info file?

### ISSUE THREAD

**Issue by rushairer** [Ytemiloluwa/PodcastApp#8]
```
Thread 1: Fatal error: BASE_URL not available in plist file

```

**Comment by Ytemiloluwa** [comment]
<img width="1142" alt="Screenshot 2023-06-28 at 15 33 42" src="https://github.com/Ytemiloluwa/Chorcast/assets/91268094/cbd8f150-7270-4216-96dc-a469bb9f6f74">

Add a Custom iOS Target Property, That should fix the problem.

**Comment by rushairer** [comment]
Thank you
